### ISSUE TITLE
Error install in redmine 4.0.4

### ISSUE THREAD

**Issue by koren85** [Smile-SA/redmine_queries_for_time_report#1]
Hi!
I got error when install plugin in my redmine:

```
Migrating plugins. Please be patient, this could take a while...
rake aborted!
NameError: uninitialized constant SmileTools
/home/redmine/redmine/plugins/redmine_queries_for_time_report/init.rb:76:in `block in <top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `instance_exec'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:605:in `catch'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:199:in `block in halting'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `invoke_before'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:131:in `run_callbacks'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.3/lib/active_support/reloader.rb:89:in `prepare!'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/application.rb:337:in `require'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
```
my redmine 
```
Environment:
  Redmine version                4.0.4.stable
  Ruby version                   2.4.6-p354 (2019-04-01) [x86_64-linux-gnu]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.3
  Mercurial                      3.7.3
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.21.0
  Filesystem                     
Redmine plugins:
  no plugin installed
```

**Comment by Utopism** [comment]
Hi, fixed with last commit.
Feel free to test it, thanks.
