### ISSUE TITLE
error in redmine 4.1.x

### ISSUE THREAD

**Issue by koren85** [Smile-SA/redmine_queries_for_time_report#2]
hi! i get error after install plugin

```
root@0352e665be98:/home/redmine/redmine/log# cat ./unicorn.stderr.log
I, [2020-04-22T07:29:59.559981 #257]  INFO -- : Refreshing Gem list
/home/redmine/redmine/plugins/redmine_queries_for_time_report/init.rb:74:in `<top (required)>': undefined method `to_prepare' for nil:NilClass (NoMethodError)
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
        from /home/redmine/redmine/lib/redmine/plugin.rb:181:in `block in load'
        from /home/redmine/redmine/lib/redmine/plugin.rb:172:in `each'
        from /home/redmine/redmine/lib/redmine/plugin.rb:172:in `load'
        from /home/redmine/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `block in load'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:663:in `block in load_config_initializer'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:662:in `load_config_initializer'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `each'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `block in <class:Engine>'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
        from /usr/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `each'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `tsort_each_child'
        from /usr/lib/ruby/2.4.0/tsort.rb:415:in `call'
        from /usr/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/2.4.0/tsort.rb:347:in `each'
        from /usr/lib/ruby/2.4.0/tsort.rb:347:in `call'
        from /usr/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
        from /usr/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
        from /home/redmine/redmine/config/environment.rb:16:in `<top (required)>'
        from config.ru:4:in `require'
        from config.ru:4:in `block in <main>'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.2.2/lib/rack/builder.rb:125:in `instance_eval'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.2.2/lib/rack/builder.rb:125:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.5.4/lib/unicorn.rb:54:in `eval'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.5.4/lib/unicorn.rb:54:in `block in builder'
        from /home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/unicorn-5.5.4/bin/unicorn_rails:139:in `block in rails_builder'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.5.4/lib/unicorn/http_server.rb:794:in `build_app!'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.5.4/lib/unicorn/http_server.rb:141:in `start'
        from /home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/unicorn-5.5.4/bin/unicorn_rails:209:in `<top (required)>'
        from /home/redmine/redmine/vendor/bundle/ruby/2.4.0/bin/unicorn_rails:23:in `load'
        from /home/redmine/redmine/vendor/bundle/ruby/2.4.0/bin/unicorn_rails:23:in `<main>'
```

**Comment by Utopism** [comment]
Hi @koren85, it seems that there is an issue with your unicorn configuration, because **to_prepare** is called with on core **Rails.configuration** object,
Perhaps you have to enable **preload_app** in unicorn configuration :
See :
* https://stackoverflow.com/questions/18895433/referring-to-rails-from-the-unicorn-config-file
* https://yhbt.net/unicorn/Unicorn/Configurator.html#method-i-preload_app

**Comment by Utopism** [comment]
Closing this issue, as this is not due to an error in the plugin.
